[package]
name = "comfyTable"
version = "0.1.0"

[dependencies]
unicodeWidth = { git = "https://github.com/mcdearman/meadow-unicode-width" }
unicodeSegmentation = { git = "https://github.com/mcdearman/meadow-unicode-segmentation" }
